name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        env:
          CI_USER: ${{ GITHUB_REPOSITORY_OWNER }}
          CI_EMAIL: ${{ secrets.REPOSITORY_OWNER_EMAIL }}
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'Updated Changelog to $VERSION' && echo "push=true" >> $GITHUB_ENV || echo "No changes to Changelog $VERSION"

      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ GITHUB_REPOSITORY_OWNER }}
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
