name: luacheck
on: [push, pull_request]
jobs:
  lint:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          luacheckrc_url: https://raw.githubusercontent.com/Hoidberg/ClassicEngineV2/master/.luacheckrc
