name: luacheck
on: [push, pull_request]
jobs:
  lint:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: Jayrgo/luacheck-action@v1
        with:
          # List of files, directories and rockspecs to check.
          # Default: .
          files: '.'

          # Path to configuration file.
          # Default: .luacheckrc
          config: '.luacheckrc'

          # Arguments passed to luacheck.
          # Default: -q
          args: '-q'
